# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a200tfbg676-2

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/mist/Bairak_labs/lab_1.cache/wt [current_project]
set_property parent.project_path /home/mist/Bairak_labs/lab_1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part xilinx.com:ac701:part0:1.2 [current_project]
read_vhdl -library xil_defaultlib {
  /home/mist/Bairak_labs/lab_1.srcs/sources_1/new/l_block_wrr.vhd
  /home/mist/Bairak_labs/lab_1.srcs/sources_1/new/full_scheme.vhd
  /home/mist/Bairak_labs/lab_1.srcs/sources_1/new/inp_buff.vhd
  /home/mist/Bairak_labs/lab_1.srcs/sources_1/new/c_block.vhd
  /home/mist/Bairak_labs/lab_1.srcs/sources_1/new/c_full_scheme.vhd
  /home/mist/Bairak_labs/lab_1.srcs/sources_1/new/new_full_scheme.vhd
}
read_xdc /home/mist/Bairak_labs/lab_1.srcs/constrs_1/new/lab_1.xdc
set_property used_in_implementation false [get_files /home/mist/Bairak_labs/lab_1.srcs/constrs_1/new/lab_1.xdc]

synth_design -top new_full_scheme -part xc7a200tfbg676-2
write_checkpoint -noxdef new_full_scheme.dcp
catch { report_utilization -file new_full_scheme_utilization_synth.rpt -pb new_full_scheme_utilization_synth.pb }
